### ISSUE TITLE
Vulnerability in older versions of coreos/etcd

### ISSUE THREAD

**Issue by ShubhamPalriwala** [gardener/controller-manager-library#39]
**What happened**:
The package https://github.com/coreos/etcd has a vulnerability that has been fixed in its latest versions. 

**What you expected to happen**:
Can you upgrade the dependencies, specifically this, so that we can use the logger freely,

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
We use it at Kyverno and our SAST tool Nany is throwing an error for this. Any sort of help here is appreciated
https://github.com/kyverno/kyverno/issues/2950#issuecomment-1012018809
**Environment**:

**Comment by MartinWeindel** [comment]
Thanks for reporting! The controller-manager-library does not use any code from the  package "github.com/coreos/etcd", but I can conform it is indirectly referenced as a dependency in go.sum. 
I'm in the process to update some dependencies to get rid of this package. It looks good as it has gone already on my local dev branch, but it may take some time (days) to validate my changes. Please also note that we do not make releases for this library regularly.

Honestly, if you are only using the logging package, I would look for an alternative.

**Comment by MartinWeindel** [comment]
fixed with #40
